api:
  dashboard: true
  insecure: true

log:
  level: DEBUG
  filePath: /logs/traefik.log

accessLog:
  filePath: /logs/access.log
  format: common

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"


# TLS configuration
tls:
  stores:
    default:
      # Default cert for local domains (fallback)
      defaultCertificate:
        certFile: "/certs/local.crt"  # mkcert or self-signed
        keyFile: "/certs/local.key"

providers:
  docker: {}
  file:
    filename: "/etc/traefik/dynamic_conf.yml"
    watch: true

certificatesResolvers:
  le:
    acme:
      email: huzaifairfan2001@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
